// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsqffbtheeqenhewyqic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzcWZmYnRoZWVxZW5oZXd5cWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDE2NzAsImV4cCI6MjA2MjM3NzY3MH0._b8GHi3phGDL-k0R9cvf1vy3g4TqK7mGK93dUpzqYAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);