
import React from "react"
import {
  Loader2,
  X,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronsUpDown,
  Plus,
  Minus,
  Search,
  LogIn,
  LogOut,
  Settings,
  User,
  Calendar,
  Bell,
  Mail,
  Menu,
  Home,
  Sliders,
  SlidersHorizontal,
  Link,
  ExternalLink,
  Eye,
  EyeOff,
  Key,
  Lock,
  Unlock,
  Info,
  AlertTriangle,
  Edit,
} from "lucide-react"

export type IconProps = React.HTMLAttributes<SVGElement>

export const Icons = {
  spinner: Loader2,
  close: X,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronsUpDown: ChevronsUpDown,
  plus: Plus,
  minus: Minus,
  search: Search,
  logIn: LogIn,
  logOut: LogOut,
  settings: Settings,
  user: User,
  calendar: Calendar,
  bell: Bell,
  mail: Mail,
  menu: Menu,
  home: Home,
  sliders: Sliders,
  slidersHorizontal: SlidersHorizontal,
  link: Link,
  externalLink: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  key: Key,
  lock: Lock,
  unlock: Unlock,
  info: Info,
  alertTriangle: AlertTriangle,
  edit: Edit,
}
